---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springci/graalvm-ce-java8
    tag: 20.0.0-dev_20200121-1000

inputs:
  - name: spring-graal-native

run:
  path: spring-graal-native/ci/build.sh
