---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springci/graalvm-ce-java8
    tag: 20.1.0-dev_20200125-1203

inputs:
  - name: spring-graal-native

run:
  path: spring-graal-native/ci/build.sh
